version: "3"
services:
  book-catalog:
    build:
      context: book_catalog
      dockerfile: Dockerfile
    image: ${CONTAINER_REGISTRY}/book-catalog:${VERSION}
    container_name: book-catalog
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=${DATABASE_URL}
  inventory:
    build:
      context: inventory_management
      dockerfile: Dockerfile
    image: ${CONTAINER_REGISTRY}/inventory-management:${VERSION}
    container_name: inventory-management
    ports:
      - 8001:8001
    environment:
      - DATABASE_URL=${DATABASE_URL}