apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-deployment
spec:
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
        - name: book-catalog
          image: $CONTAINER_REGISTRY/book-catalog:$VERSION
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: $DATABASE_URL
        - name: inventory-management
          image: $CONTAINER_REGISTRY/inventory-management:$VERSION
          ports:
            - containerPort: 8001
          env:
            - name: DATABASE_URL
              value: $DATABASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  selector:
    app: microservice
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  selector:
    app: microservice
  ports:
    - port: 8001
      targetPort: 8001
  type: LoadBalancer